### ISSUE TITLE
Leaflet crash when drawing polyline

### ISSUE THREAD

**Issue by gluebi** [veitbjarsch/vue-leaflet-markercluster#13]
Repro-Repo: https://github.com/gluebi/vue-leaflet-marker-polyline-repro

When opening the popup of a marker the polyline should be drawn.

The line is drawn but the popup doesn't open because of the crash.

```
Uncaught (in promise) TypeError: Cannot use 'in' operator to search for '_leaflet_id' in undefined
    at stamp (Util.js:55:8)
    at NewClass.removeLayer (Layer.js:180:12)
    at RefImpl.removeLayer (vue-leaflet.es.js:1324:29)
    at t (vue-leaflet.es.js:55:22)
    at vue-leaflet.es.js:305:5
    at runtime-core.esm-bundler.js:2675:88
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:17)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2655:19)
    at invokeArrayFns (shared.esm-bundler.js:77:10)
```

The same works as long as the markers are not inside of the marker cluster.

I am not a 100% certain if the problem lies in `vue-leaflet-markercluster` or in `vue-leaflet`.
Let me know if I should open an issue in their repo instead.

Thanks!

**Comment by veitbjarsch** [comment]
Hi, thanks for creating a repo to reproduce the big. I'll have a look into it later this week and will get back to you asap.

**Comment by veitbjarsch** [comment]
Okay just checked your code. Not sure if it is a requirement of leaflet itself, but as far I found out for vue-leaflet you need to wrap the polyline in a feature group:
```
<l-feature-group>
      <l-polyline
          v-if="isVehiclePopupOpen"
          :lat-lngs="[
            { lat: 55, lng: 10 },
            { lat: 56, lng: 11 },
          ]"
          color="red"
      />
</l-feature-group>
```

This will fix your error. So the error definitely isn't related to  `vue-leaflet-markercluster`. Might be an error or an requirement of `vue-leaflet`.

**Comment by gluebi** [comment]
Thank you for the quick solution. Very much appreciated! Closing the issue then.
