### ISSUE TITLE
Super slow and stuttering zoom

### ISSUE THREAD

**Issue by ruilvo** [veitbjarsch/vue-leaflet-markercluster#14]
Hello,
First of all, thanks for the plugin.

I'm trying to use it with a cluster of around 250 elements.
However, zooming stutters a lot, with lags in the order of several seconds:
https://i.gyazo.com/db929377681aa9ca2a7f06c745618086.mp4

The example seems to handle around 380 just fine: 
https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html

What can I do?

**Comment by veitbjarsch** [comment]
Hi,

thanks for your feedback. I also implemented a demo in the playground with 10.000 entries. This demo runs without a noticeable lag on zooming. Would it be possible to provide a demo, which illustrate the problem, so I check and debug the issue. 

Thanks

**Comment by veitbjarsch** [comment]
@ruilvo Do you had the chance to create any demo for this issue, or did you already solved this problem?

**Comment by ruilvo** [comment]
Sorry, haven't had the time to work on this. I'll close it and reopen when I get the time to debug the issue any further if the need arises.
