### ISSUE TITLE
Quickstart isn't working as quick as it says

### ISSUE THREAD

**Issue by nikitastetskiy** [veitbjarsch/vue-leaflet-markercluster#5]
Hello,

Maybe I am missing something, but I can't get it working with my project. So, I follow your instructions as bellow:

First installing all the components in this order
```
npm install leaflet
npm i @vue-leaflet/vue-leaflet
npm i -D vue-leaflet-markercluster
```
Then I copy your quickstart in the readme and it gives me error at the last line:
```
import 'vue-leaflet-markercluster/styles'
```
That line isn't showing in your playground app. If I delete the line, it will display the following error:
```
vue-leaflet-markercluster.es.js:8 Uncaught ReferenceError: L is not defined
    at vue-leaflet-markercluster.es.js:8:13
    at vue-leaflet-markercluster.es.js:6:5
    at vue-leaflet-markercluster.es.js:7:3
    at vue-leaflet-markercluster.es.js:1016:1
```
I am sorry that I can't get a little more deeper into the problem and troubleshoot it, but any help will be appreciated!

**Comment by nikitastetskiy** [comment]
OK, got it working changing this line:
```
import 'vue-leaflet-markercluster/dist/style.css'
```
Also needed to add the following at main.js:
```
import L from 'leaflet'
globalThis.L = L
```

**Comment by veitbjarsch** [comment]
Good catch. Yeah missed this in the description. I'll add it later to the readme. Thanks for the feedback.

**Comment by veitbjarsch** [comment]
Okay quickstart should now work as expected. Also released a patch to npm, so the readme there shows also the correct block.
Thanks again for your feedback. If you face any difficulties feel free to open another thread. Please keep in mind that the current version is an alpha and I didn't tested all functionality yet.
